name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main # Adjust this to the branch you want to trigger deployments from

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Install Flutter
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      # Build the Flutter Web project
      - name: Build Flutter Web
        run: flutter build web --release

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web

      # Update the repository description
      - name: Update Repository Description
        env:
          REPO: ${{ github.repository }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          URL="https://${{ github.repository_owner }}.github.io/${{ github.repository }}"
          curl -X PATCH \
            -H "Authorization: token $TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/$REPO \
            -d "{\"description\": \"Deployed at $URL\"}"
